#!/bin/bash

# OPENAI_API_KEY
OPENAI_API_KEY='YOUR_OPEN_AI_KEY'

# WECOM_WEBHOOK_URL
WECOM_WEBHOOK_URL='YOUR_WECOM_WEB_HOOK'

export OPENAI_API_KEY=$OPENAI_API_KEY
export WECOM_WEBHOOK_URL=$WECOM_WEBHOOK_URL